#!/bin/sh

export OFToolkit=$PWD
export PATH=${OFToolkit}/bin:$PATH

export SADPath="/Applications/SAD/SAD"
alias SAD=$SADPath/bin/gs

PythonP=$(which python3)

#sed -i "s|66TOOLPAHT99|$OFToolkit|g" $OFToolkit/template/sad_BGS2

for i in bin/*.py
do
        sed -i "s|66PYTHONPATH99|$PythonP|g" $i
done